#!/bin/sh
set -e
git submodule update --init

cp "$(fc-match sans-serif -f '%{file}')" assets/font.ttf

nix-shell shell.nix --command './gradlew assembleDebug --no-daemon'

mkdir -p .io/o
cp build/outputs/apk/debug/Unexpected-Keyboard-debug.apk .io/o
